error: stack trace saving and printing
Furthermore, assertion failures as well as panic() end up printing the stack
trace.

This change assumes the system has addrtosymstr().

Signed-off-by: Josef 'Jeff' Sipek <jeffpc@josefsipek.net>