sexpr: enable verbose parser error messages
This way, instead of the extremely unhelpful:

	Error: syntax error

we get a significantly more useful:

	Error: syntax error, unexpected NUMBER, expecting $end

Signed-off-by: Josef 'Jeff' Sipek <jeffpc@josefsipek.net>