error: wrap assfail/__assert in a helper function
Instead of mimicking a very specific function signature, let's make our own
function that we can change as we please.

Signed-off-by: Josef 'Jeff' Sipek <jeffpc@josefsipek.net>